# Generated by Django 4.2.29 on 2026-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('warehouse_manager', 'Warehouse Manager'), ('delivery_person', 'Delivery Person'), ('marketing_person', 'Marketing Person')], default='admin', max_length=20),
        ),
    ]
