# Generated by Django 4.2.29 on 2026-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_migrate_old_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
