# Generated by Django 4.2.29 on 2026-04-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_vehicle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle_number',
        ),
    ]
