# Generated by Django 4.2.29 on 2026-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('warehouse_manager', 'Warehouse Manager'), ('delivery_person', 'Delivery Person'), ('marketing_person', 'Marketing Person'), ('cutter', 'Cutter')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle Number'),
        ),
    ]
