# Generated by Django 4.2.29 on 2026-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
