# Generated by Django 4.2.29 on 2026-04-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_party_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name_plural': 'Parties'},
        ),
    ]
