# Generated by Django 4.2.27 on 2026-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
