# Generated by Django 4.2.29 on 2026-04-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        ('payments', '0001_initial'),
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='partybalance',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='parties.party'),
        ),
    ]
