# Generated by Django 4.2.29 on 2026-04-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0003_alter_party_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('distributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_distributions', to='parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='CataloguePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_purchases', to='parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalogue_visits/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_visits', to='parties.party')),
                ('visited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueVisitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('catalogue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.cataloguetype')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogues.cataloguevisit')),
            ],
        ),
        migrations.CreateModel(
            name='CataloguePurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('catalogue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.cataloguetype')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogues.cataloguepurchase')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('catalogue_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalogues.cataloguetype')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogueDistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('catalogue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.cataloguetype')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogues.cataloguedistribution')),
            ],
        ),
    ]
