# Generated by Django 4.2.29 on 2026-04-15 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_vendor'),
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepurchase',
            name='party',
        ),
        migrations.AddField(
            model_name='cataloguepurchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_purchases', to='parties.vendor'),
        ),
    ]
