# Generated by Django 4.2.29 on 2026-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_remove_cataloguepurchase_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguepurchase',
            name='tagging_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cataloguepurchase',
            name='via',
            field=models.CharField(blank=True, help_text='e.g. Courier, In Hand, etc.', max_length=100, null=True),
        ),
    ]
