# Generated by Django 4.2.29 on 2026-04-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_cataloguepurchase_tagging_done_cataloguepurchase_via'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cataloguepurchase',
            name='tagging_done',
        ),
        migrations.RemoveField(
            model_name='cataloguepurchase',
            name='via',
        ),
    ]
