# Generated by Django 4.2.29 on 2026-04-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cloth_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.clothtype')),
            ],
        ),
    ]
