# Generated by Django 4.2.29 on 2026-04-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_collection_designtype_purchaseentry_purchaseitem_and_more'),
        ('orders', '0003_remove_order_cutter_remove_order_dispatcher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothType',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='design_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.designtype'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseentry'),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.purchaser'),
        ),
        migrations.AddField(
            model_name='designtype',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='inventory.collection'),
        ),
        migrations.AddField(
            model_name='stock',
            name='design_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.designtype'),
        ),
    ]
