# Generated by Django 4.2.29 on 2026-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delete_clothtype_purchaseitem_design_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtype',
            name='alias1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designtype',
            name='alias2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designtype',
            name='alias3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designtype',
            name='alias4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designtype',
            name='alias5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
