# Generated by Django 4.2.29 on 2026-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_designtype_alias1_designtype_alias2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='reference_bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
