# Generated by Django 4.2.27 on 2026-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_designtype_unique_name_per_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='tagging_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='via',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
