# Generated by Django 4.2.29 on 2026-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Interior Soft', max_length=255)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_qr_code', models.ImageField(blank=True, null=True, upload_to='shop_qr/')),
            ],
            options={
                'verbose_name': 'Shop Configuration',
                'verbose_name_plural': 'Shop Configuration',
            },
        ),
    ]
