# Generated by Django 4.2.29 on 2026-04-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopconfiguration',
            name='upi_qr_code',
        ),
    ]
