# Generated by Django 4.2.29 on 2026-04-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_config', '0002_remove_shopconfiguration_upi_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfiguration',
            name='shop_name',
            field=models.CharField(default='Bluebell Interiors', max_length=255),
        ),
    ]
