# Generated by Django 4.2.29 on 2026-04-11 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_collection_designtype_purchaseentry_purchaseitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cutter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dispatcher',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth_type',
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='design_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.designtype'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
