# Generated by Django 4.2.29 on 2026-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_cutter_remove_order_dispatcher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('self', 'Self'), ('porter', 'Porter'), ('courier', 'Courier')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
