# Generated by Django 4.2.29 on 2026-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('self', 'Self'), ('porter', 'Porter'), ('courier', 'Courier'), ('delivery_man', 'Delivery Man')], default='self', max_length=20),
        ),
    ]
